# Generated by Django 5.0.6 on 2024-07-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='orders',
            field=models.TextField(default='[]'),
        ),
    ]
