# Generated by Django 5.0.6 on 2024-07-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_menu_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, default='./menu/default.jpg', null=True, upload_to='menu'),
        ),
    ]
