# Generated by Django 5.0.6 on 2024-07-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='qty',
            field=models.IntegerField(default='1'),
        ),
    ]
