# Generated by Django 5.0.6 on 2024-07-08 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_menu_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='menu_qty',
            new_name='menuQty',
        ),
    ]
