# Generated by Django 5.0.6 on 2024-07-09 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_rename_menu_qty_cart_menuqty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='qty',
        ),
    ]
